project:
  type: website


website:
  title: "University of Dundee Mathematics"
  google-analytics: "G-MQD60ZZ43S"
  navbar:
    logo: "UoD_logo_RGB.png"



format:
  html:
    theme: cosmo
    css: styles.css



